title: Adrian Isinta
logo: /assets/img/profile.jpg
description: Cybersecurity | Penetration Testing | Cloud Security Enthusiast

remote_theme: mmistakes/minimal-mistakes@4.24.0

# Build settings
plugins:
  - jekyll-include-cache

# Optional: Google Analytics (leave blank if not using)
google_analytics: ""
