title: Adrian Isinta
logo: /assets/img/profile.jpg
description: Cybersecurity | Penetration Testing | Cloud Security Enthusiast
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

navigation:
  - title: Home
    url: /
  - title: Resume
    url: /resume
  - title: Projects
    url: /projects
  - title: Lab Challenges
    url: /labs
  - title: Contact
    url: /contact
